### PR TITLE
To mesosphere

### PR DESCRIPTION
**Pull request by BenWhitehead**
Per offline discussion with the mesos project maintainers, this project will no longer live under the mesos organization on github. Instead, it will live under the Mesosphere organization and be linked to by the mesos project.

### CODE REVIEW

**Comment by BenWhitehead** [comment]
Fixes #30

**Comment by BenWhitehead** [comment]
@cruhland Can you do a quick review before I squash and merge?

**Comment by BenWhitehead** [comment]
javadoc build error is fixed in #32

**Comment by cruhland** [comment]
Ship it :+1:

**Pull request merged**
